version: '3.8'

services:
  telegram-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-mcp
    # Load environment variables from a .env file in the same directory
    env_file:
      - .env
    # Keep stdin open and allocate a pseudo-TTY, crucial for stdio MCP servers
    stdin_open: true
    tty: true
    # Mount a local directory for persisting the Telegram session file
    # This is only needed if NOT using TELEGRAM_SESSION_STRING
    volumes:
      - ./telegram_sessions:/app/sessions
    restart: unless-stopped 